create table public.news (
    id bigint generated by default as identity primary key,

    source text not null default 'rockstar_newswire',

    title text not null,

    url text not null unique,

    raw_content text,

    published_at timestamptz,

    image_url text,

    classifier text,

    collected_at timestamptz not null default now()
);