create table public.scripts (
    id bigint generated by default as identity primary key,

    news_id bigint references public.news(id) on delete cascade,

    youtube_script text,
    instagram_script text,

    created_at timestamptz not null default now()
);